// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("0.1.0722.2022")]
[assembly: AssemblyFileVersion("0.1.0722.2022")]
[assembly: AssemblyInformationalVersion("0.1.0722.2022")]
